//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBuisnessSupplies
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OrderDetails
    {
        public long ID_Order { get; set; }
        public long ID_Stock { get; set; }
        public string PrName { get; set; }
        public short Quantity { get; set; }
        public decimal PrCost { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
