//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBuisnessSupplies
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Stocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocks()
        {
            this.OrderDetails = new ObservableCollection<OrderDetails>();
        }
    
        public long ID_Stock { get; set; }
        public long ID_Product { get; set; }
        public string ProductSpecification { get; set; }
        public long ID_Provider { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public int StockBalance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<OrderDetails> OrderDetails { get; set; }
        public virtual ProductCatalog ProductCatalog { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
