//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBuisnessSupplies
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class VW_ProductsCatalog
    {
        public string ProductName { get; set; }
        public string ProductSpecification { get; set; }
        public int StockBalance { get; set; }
        public string Organization { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
    }
}
